# Generated by Django 4.1.1 on 2022-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_video_remove_post_category_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, upload_to='image, null=True'),
        ),
    ]
