# Generated by Django 4.1.1 on 2022-09-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_video_file_alter_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
